### ISSUE TITLE
Connect Canoe use instructions with map

### ISSUE THREAD

**Issue by C14H14N2O4** [fodr-arm/dumoine-river#7]
Connect the canoe use/river crossing instruction from the background page to the two campsites on the web map associated with the Fildegrand River Crossing/ the pop up for the crossing.

**Comment by C14H14N2O4** [comment]
Reminder to do it to french map as well

**Comment by C14H14N2O4** [comment]
French will have to wait for translation

**Comment by C14H14N2O4** [comment]
Link to English

**Comment by carolbuckingham** [comment]
pushed the changes to addFrench branch since the page doesn't exist on main yet
